### ISSUE TITLE
Demo page broken

### ISSUE THREAD

**Issue by SinghManvir** [malbarmavi/mat-table-column-filter#10]
Getting 404 - site not found on the demo page.

**Comment by malbarmavi** [comment]
sorry 😅 I have change my GitHub username and this broke the demo url , I have fixed 👉 [her](http://bit.ly/material-columns-filter) 

another option you can use **stackblitz** to clone any angular project and run it  [https://stackblitz.com/github/malbarmavi/mat-table-column-filter/  ](https://stackblitz.com/github/malbarmavi/mat-table-column-filter/  )
